const publicationsData = [
  {
    "Title": "Managing Opinion Spamming with AI in Regulatory Public Engagement",
    "URL": "https://www.researchgate.net/publication/389841717_Managing_Opinion_Spamming_with_AI_in_Regulatory_Public_Engagement?_sg=33mRwTXTcnfxlM5P5994JS_eGrX6iwhF25GZjYRztjGjnPNHUR_CndViWuDGO_V4avTEuw6eBkPoTiZWTPrIplmy9Rk&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiX2RpcmVjdCJ9fQ",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/389841717_Managing_Opinion_Spamming_with_AI_in_Regulatory_Public_Engagement?_sg=33mRwTXTcnfxlM5P5994JS_eGrX6iwhF25GZjYRztjGjnPNHUR_CndViWuDGO_V4avTEuw6eBkPoTiZWTPrIplmy9Rk&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoiX2RpcmVjdCJ9fQ",
    "Date": "Mar 2025",
    "Recommentation": "2 Recommendations",
    "Summary": "",
    "Option 1": "",
    "URL3": "",
    "Date2": "Mar 2025",
    "ETC": ""
  },
  {
    "Title": "Efficient Duplicate Comment Detection for Rulemaking Agencies With Unsupervised Deep Learning: A Cost-Effective and High-Accuracy Approach",
    "URL": "https://www.researchgate.net/publication/387817013_Efficient_Duplicate_Comment_Detection_for_Rulemaking_Agencies_With_Unsupervised_Deep_Learning_A_Cost-Effective_and_High-Accuracy_Approach?_sg=_HakdH_ZGLXT07Q3OeJnMLZ9IVHd12brMyyomu0NoW4RkQMnkZ1Gh-MVQS1dT19eE6QEMygvUgTpHk2H-r8SahC_gUs",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/387817013_Efficient_Duplicate_Comment_Detection_for_Rulemaking_Agencies_With_Unsupervised_Deep_Learning_A_Cost-Effective_and_High-Accuracy_Approach?_sg=_HakdH_ZGLXT07Q3OeJnMLZ9IVHd12brMyyomu0NoW4RkQMnkZ1Gh-MVQS1dT19eE6QEMygvUgTpHk2H-r8SahC_gUs",
    "Date": "Jan 2025",
    "Recommentation": "4 Recommendations",
    "Summary": "Government agencies tasked with soliciting comments from the American public in response to changes in rulemaking have long been interested in finding effective techniques to automatically process spam comments, including flagging and filtering duplicate comments. Duplicate submissions are problematic because they obscure genuine public input and may amplify fringe opinions nonrepresentative of the majority of the American public. Given that duplicate comments are generated from templates or predrafted texts, they can easily overwhelm the commenting process, and massive opinion spam campaigns have made manually flagging duplicate comments a costly and time-consuming task for rulemaking agencies. To help agencies in their deduplication efforts, we developed and tested a highly accurate and cost-effective technique based on unsupervised deep machine learning. Our method used the graph augmented deep learning model to embed the comment texts into vectors, and then we applied the clustering method to the embedded vectors to identify similar comments. To test the efficacy of the proposed approach, we applied our technique to the raw data from the Federal Communications Commission’s (FCC) proposed rule change on Net Neutrality in 2017. Our study results demonstrate the superiority of the proposed deep learning technique at identifying duplicate comments, relative to other state-of-the-art deduplication approaches.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Jan 2025",
    "ETC": ""
  },
  {
    "Title": "Mapping Media Research Paradigms: Journalism & Mass Communication Quarterly ’s Century of Scientific Evolution",
    "URL": "https://www.researchgate.net/publication/376706085_Mapping_Media_Research_Paradigms_Journalism_Mass_Communication_Quarterly_%27s_Century_of_Scientific_Evolution?_sg=aGG-C49Ufzvt4D1px5L1bpx1Y4yb_WlOZ-k414nw0WOekPksLRkXvu0JegitE6fX4mWT49h57nBZ_ZurxonyHardKwg",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/376706085_Mapping_Media_Research_Paradigms_Journalism_Mass_Communication_Quarterly_%27s_Century_of_Scientific_Evolution?_sg=aGG-C49Ufzvt4D1px5L1bpx1Y4yb_WlOZ-k414nw0WOekPksLRkXvu0JegitE6fX4mWT49h57nBZ_ZurxonyHardKwg",
    "Date": "Dec 2023",
    "Recommentation": "1 Recommendation",
    "Summary": "This retrospective review of nearly a century of publications in Journalism and Mass Communication Quarterly (JMCQ) traces the maturation of media studies toward a scientific discipline. The field’s dominant paradigms—media effects and communicator uses—persist, adapt, and diversify over time, yielding actionable insights. Challenges include (a) bridging older and newer media theories, (b) harnessing data science, and (c) capitalizing on artificial intelligence/machine learning (AI/ML). Future media research can conceptualize evolving three-dimensional interactions among media, people, and AI. We propose seven initiatives for the next century: revisiting classical theories, fostering interdisciplinary collaboration, balancing descriptive and prescriptive theorization, nurturing indigenous theorizing, collaborating with industry, reverse theorizing with AI, and exploring and regulating AI’s role in media.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Dec 2023",
    "ETC": ""
  },
  {
    "Title": "Conceptualizing Conspiratorial Thinking: Explicating Public Conspiracism for Effective Debiasing Strategy",
    "URL": "https://www.researchgate.net/publication/371675993_Conceptualizing_Conspiratorial_Thinking_Explicating_Public_Conspiracism_for_Effective_Debiasing_Strategy?_sg=MQ_BAn0CVcJOcGZgkvg9VS5qlm2CRVsApcf9_9vYGxpYzoM3vC9WWr3p9mlt0ZiCywfYf5hUJAQgBeZewUWkxwz668c",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/371675993_Conceptualizing_Conspiratorial_Thinking_Explicating_Public_Conspiracism_for_Effective_Debiasing_Strategy?_sg=MQ_BAn0CVcJOcGZgkvg9VS5qlm2CRVsApcf9_9vYGxpYzoM3vC9WWr3p9mlt0ZiCywfYf5hUJAQgBeZewUWkxwz668c",
    "Date": "Jun 2023",
    "Recommentation": "",
    "Summary": "We use the situational theory of problem solving to explicate how publics engage in conspiratorial thinking as a form of cognitive problem solving. In doing so, we develop a new typology of conspiracy theories and introduce conceptual definitions and operationalizations of conspiratorial thinking as both dispositional and situational. We conduct two survey studies which provide evidence of the measures’ reliability and validity. We also investigate the debiasing effects of relational and informational strategies employed by social institutions. Finally, we present institutional behavioral strategies, grounded in the strategic behavioral theory of communication management, that can reduce conspiratorial thinking. Our new concepts and measurement approaches describe the origins and processes of public conspiracism and provide a foundation for implementing ethical and effective interventions, ultimately contributing to a more informed and educated society.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Jun 2023",
    "ETC": ""
  },
  {
    "Title": "Fans, friends, critics, and foes: How CSR-based stakeholder segmentation differentiates perceived corporate ethics, trust, and perceived brand quality",
    "URL": "https://www.researchgate.net/publication/371211931_Fans_friends_critics_and_foes_How_CSR-based_stakeholder_segmentation_differentiates_perceived_corporate_ethics_trust_and_perceived_brand_quality?_sg=7uhMska-yfxefDVhJKEPC0W5Z49jTMol-xIVeVAGCoITIViDZS_55P_fNAo6oQkHNrf0RtGM8jL-Dkujqm4MlbhNoJk",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/371211931_Fans_friends_critics_and_foes_How_CSR-based_stakeholder_segmentation_differentiates_perceived_corporate_ethics_trust_and_perceived_brand_quality?_sg=7uhMska-yfxefDVhJKEPC0W5Z49jTMol-xIVeVAGCoITIViDZS_55P_fNAo6oQkHNrf0RtGM8jL-Dkujqm4MlbhNoJk",
    "Date": "Jun 2023",
    "Recommentation": "1 Recommendation",
    "Summary": "",
    "Option 1": "",
    "URL3": "",
    "Date2": "Jun 2023",
    "ETC": ""
  },
  {
    "Title": "Finding Self-Salvation for the Ill-Informed Society: A Summary of Empirical Studies",
    "URL": "https://www.researchgate.net/publication/371065772_Finding_Self-Salvation_for_the_Ill-Informed_Society_A_Summary_of_Empirical_Studies?_sg=DFUByPWWRER6BmjOay5CHDLsB3KYwY_ejTbYCzydjZZhFcd_MgzjUXyromIpYyRXNYTS1D_l3Pr4xscc4ib32SwFsM4",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/371065772_Finding_Self-Salvation_for_the_Ill-Informed_Society_A_Summary_of_Empirical_Studies?_sg=DFUByPWWRER6BmjOay5CHDLsB3KYwY_ejTbYCzydjZZhFcd_MgzjUXyromIpYyRXNYTS1D_l3Pr4xscc4ib32SwFsM4",
    "Date": "May 2023",
    "Recommentation": "3 Recommendations",
    "Summary": "The internet was once seen as a beacon of hope for democratizing public access to information, but scholars argue that social media has led to frustration, isolation, and pseudo-information. This volume presents empirical studies exploring paths to potentially rebuild ideal communication situations, if ever, in the digital age and cope with digital information failure. Can we salvage an ill-informed society? These studies offer insights into addressing these issues.",
    "Option 1": "",
    "URL3": "",
    "Date2": "May 2023",
    "ETC": ""
  },
  {
    "Title": "Situational theory of problem solving (STOPS): A foundational theory of publics and its behavioral nature in problem solving",
    "URL": "https://www.researchgate.net/publication/366934564_Situational_theory_of_problem_solving_STOPS_A_foundational_theory_of_publics_and_its_behavioral_nature_in_problem_solving?_sg=d-WrUlJU9nsEVVNP9LzOYIJ3RkcvVNNCDgTdx-IFuLrOYkiWOZRfVt3xBmS7ozX3FpjudHUK8f9oWQfce8Mw7kEQGFk",
    "Type": "Chapter",
    "URL2": "https://www.researchgate.net/publication/366934564_Situational_theory_of_problem_solving_STOPS_A_foundational_theory_of_publics_and_its_behavioral_nature_in_problem_solving?_sg=d-WrUlJU9nsEVVNP9LzOYIJ3RkcvVNNCDgTdx-IFuLrOYkiWOZRfVt3xBmS7ozX3FpjudHUK8f9oWQfce8Mw7kEQGFk",
    "Date": "",
    "Recommentation": "2 Recommendations",
    "Summary": "The situational theory of problem solving (STOPS) was first published in 2011 as a generalized extension of the situational theory of publics (STP) (J.-N. Kim & Grunig, 2011). STP, which was first developed in the 1970s, explores how and why people do or do not use communication to cope with life situations (Grunig, 2003). Both theories were founded on the same assumptions: 1) communication is a purposive coping mechanism that individuals undertake when experiencing a problematic situation, 2) communicative action is epiphenomenal to decision-making or problem-solving actions, and 3) communicative action is a way to determine whether to act in indeterminate situations. STOPS also introduces the communicative action in problem solving (CAPS) framework, which examines publics’ proactiveness and reactiveness in information acquisition, information selection, and information transmission (Ni & Kim, 2009). STOPS guides public relations practice to be more strategic by understanding what causes individuals to act communicatively for or against organizations.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/366934564_Situational_theory_of_problem_solving_STOPS_A_foundational_theory_of_publics_and_its_behavioral_nature_in_problem_solving?_sg=d-WrUlJU9nsEVVNP9LzOYIJ3RkcvVNNCDgTdx-IFuLrOYkiWOZRfVt3xBmS7ozX3FpjudHUK8f9oWQfce8Mw7kEQGFk",
    "Date2": "Jan 2023",
    "ETC": "Public Relations Theory III"
  },
  {
    "Title": "The situational theory of problem solving (STOPS): Past, present and future",
    "URL": "https://www.researchgate.net/publication/363422175_The_situational_theory_of_problem_solving_STOPS_Past_present_and_future?_sg=XFw2M7Lq-MBYrtgjEB-Ye046MiyTkTx4pSHdvj7RqSH5k9a3eu6m5jwlVVBPnpMwXzR02IT_UlVv8W4Le0KcH9M9hGs",
    "Type": "Chapter",
    "URL2": "https://www.researchgate.net/publication/363422175_The_situational_theory_of_problem_solving_STOPS_Past_present_and_future?_sg=XFw2M7Lq-MBYrtgjEB-Ye046MiyTkTx4pSHdvj7RqSH5k9a3eu6m5jwlVVBPnpMwXzR02IT_UlVv8W4Le0KcH9M9hGs",
    "Date": "",
    "Recommentation": "1 Recommendation",
    "Summary": "Publics can be understood as a subset of stakeholders. Unlike stakeholders, which refers to any individuals or entities that affect or are affected by organizations, publics is used in place of stakeholders in public relations as subsets of stakeholders who are segmented based on common characteristics (Rawlins, 2006). Segmentation is necessary because organizations need to prioritize their resources to build and cultivate relationships with certain publics, not all publics (J.-N. Kim et. al., 2008). The need to understand publics, how their opinions are formed, and the role they play in civil society was first developed in the 1920s as a result of the prevalence of the mass media in the formation of public opinion and individuals’ participation in civil society (J. Grunig & Kim, 2017). Some 80 years later, the situational theory of publics (STP) (J. Grunig, 2003), and the situational theory of problem solving (STOPS) (J.-N. Kim_& J. Grunig, 2011) were developed. Both theories were proposed to guide public relations practice in identifying and segmenting publics by explaining the situational factors which motivate individuals to act for or against organizations. While there are other public relations frameworks that guide segmentation in other ways, the situational factors proposed in STP and STOPS theorize why people become active in certain situations and the effects of their communicative behaviors on their cognitions, attitudes, and behaviors (Rawlins, 2006). By segmenting individuals into subsets of publics based on their motivations and communicative behaviors, organizations can better understand how to coadjust their communication and behaviors for collaborative problem-solving and mutually beneficial organization-public relationships.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/363422175_The_situational_theory_of_problem_solving_STOPS_Past_present_and_future?_sg=XFw2M7Lq-MBYrtgjEB-Ye046MiyTkTx4pSHdvj7RqSH5k9a3eu6m5jwlVVBPnpMwXzR02IT_UlVv8W4Le0KcH9M9hGs",
    "Date2": "Jan 2023",
    "ETC": "The Routledge Companion to Public Relations"
  },
  {
    "Title": "Countering Algorithmic Bias and Disinformation and Effectively Harnessing the Power of AI in Media",
    "URL": "https://www.researchgate.net/publication/365494698_Countering_Algorithmic_Bias_and_Disinformation_and_Effectively_Harnessing_the_Power_of_AI_in_Media?_sg=ljUqu3umI-p86j-joMk70z_ism5p90OhzdTs5KFnn282eEFZC-_wcAFsU2kldeLUF8sSD9U24SrxKb09QbmdyCwGX7U",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/365494698_Countering_Algorithmic_Bias_and_Disinformation_and_Effectively_Harnessing_the_Power_of_AI_in_Media?_sg=ljUqu3umI-p86j-joMk70z_ism5p90OhzdTs5KFnn282eEFZC-_wcAFsU2kldeLUF8sSD9U24SrxKb09QbmdyCwGX7U",
    "Date": "Nov 2022",
    "Recommentation": "4 Recommendations",
    "Summary": "",
    "Option 1": "",
    "URL3": "",
    "Date2": "Nov 2022",
    "ETC": ""
  },
  {
    "Title": "A duality of belief in conspiracy theories amplification: how active communicative actions work differently by trust in the Trump and Biden administrations",
    "URL": "https://www.researchgate.net/publication/363543258_A_duality_of_belief_in_conspiracy_theories_amplification_how_active_communicative_actions_work_differently_by_trust_in_the_Trump_and_Biden_administrations?_sg=D5maG0DJagyrj9AnCUJmnL2zD925dldKPHgBRz9C0SJWDOV0xSPYVzVuOWDL1TYEZFCykZNOqjJlQaX9EscIrd-dVWg",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/363543258_A_duality_of_belief_in_conspiracy_theories_amplification_how_active_communicative_actions_work_differently_by_trust_in_the_Trump_and_Biden_administrations?_sg=D5maG0DJagyrj9AnCUJmnL2zD925dldKPHgBRz9C0SJWDOV0xSPYVzVuOWDL1TYEZFCykZNOqjJlQaX9EscIrd-dVWg",
    "Date": "",
    "Recommentation": "3 Recommendations",
    "Summary": "Purpose\nThe digital setting empowers users to actively engage in communicative actions. The problem is that this active communication can increase misjudgment in determining the facts around social issues. When this communication is integrated with partisan biases, the effects can be particularly detrimental. Our study tested whether active communication actions regarding social issues and different trust levels toward presidential administrations (Trump vs. Biden) would increase belief in conspiracy theories.\n\nDesign/methodology/approach\nTo examine this, the study used online survey datasets (Amazon Mechanical Turk, N = 1355) collected during July and August 2021 concerning three political issues: the Afghanistan issue, the Black Lives Matter issue, and the Voter Fraud issue.\n\nFindings\nThe findings show that among participants with more active communication actions, the higher Trump government trust is and the lower Biden government trust is, the more belief in conspiracy theories increases. Interestingly, interaction effects of trust in government and active communicative actions were found among both Trump and Biden supporters.\n\nPractical/Social Implications\nCombined with preexisting efforts to tackle misinformation online, there are extensive efforts underway to educate laypeople about the dangers of misinformation. People must understand that any person could fall into belief in conspiracy theories if they do not carefully diagnose their information behaviors.\n\nOriginality/Value\nOur study can increase knowledge about people’s situational belief in conspiracy theories based on their political stance. The study can support future research, promoting a deeper understanding of belief in conspiracy theories.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/363543258_A_duality_of_belief_in_conspiracy_theories_amplification_how_active_communicative_actions_work_differently_by_trust_in_the_Trump_and_Biden_administrations?_sg=D5maG0DJagyrj9AnCUJmnL2zD925dldKPHgBRz9C0SJWDOV0xSPYVzVuOWDL1TYEZFCykZNOqjJlQaX9EscIrd-dVWg",
    "Date2": "Sep 2022",
    "ETC": ""
  },
  {
    "Title": "Intervening Troubled Marketplace of Ideas: How to Redeem Trust in Media and Social Institutions From Pseudo-Information",
    "URL": "https://www.researchgate.net/publication/363192121_Intervening_Troubled_Marketplace_of_Ideas_How_to_Redeem_Trust_in_Media_and_Social_Institutions_From_Pseudo-Information?_sg=WqumAVo36bQHYm2Zyb1kjFH6H0XUwkJ6EfaZq4S8dtFI_p3QkpP_yJ39rQYGF8DQCgar678aPxTBMj3luBeo78V25OE",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/363192121_Intervening_Troubled_Marketplace_of_Ideas_How_to_Redeem_Trust_in_Media_and_Social_Institutions_From_Pseudo-Information?_sg=WqumAVo36bQHYm2Zyb1kjFH6H0XUwkJ6EfaZq4S8dtFI_p3QkpP_yJ39rQYGF8DQCgar678aPxTBMj3luBeo78V25OE",
    "Date": "Sep 2022",
    "Recommentation": "2 Recommendations",
    "Summary": "Today’s public sphere is largely shaped by a dynamic digital public space where lay people conform a commodified marketplace of ideas. Individuals trade, create, and generate information, as well as consume others’ content, whereby information as public space commodity splits between this type of content and that provided by the media, and governmental institutions. This paper first explains how and why our current digital media context opens the door to pseudo-information (i.e., misinformation, disinformation, etc.). Furthermore, the paper introduces several concrete empirical efforts in the literature within a unique volume that attempt to provide specific and pragmatic steps to tackle pseudo-information, reducing the potential harm for established democracies that today’s digital environment may elicit by fueling an ill-informed society.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Sep 2022",
    "ETC": ""
  },
  {
    "Title": "Symmetry, inclusion and workplace conflicts: conflict management effects of two leadership strategies on employee advocacy and departure",
    "URL": "https://www.researchgate.net/publication/362137055_Symmetry_inclusion_and_workplace_conflicts_conflict_management_effects_of_two_leadership_strategies_on_employee_advocacy_and_departure?_sg=j-BA93pXYTu5U4lJq4RX8_Mi3Y_GZ5rqDUJdgnF_Bt5cWfyJJqGL0BicNpfoT34NWj9U9Oj_L7Vhz3OU032kcesWmHI",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/362137055_Symmetry_inclusion_and_workplace_conflicts_conflict_management_effects_of_two_leadership_strategies_on_employee_advocacy_and_departure?_sg=j-BA93pXYTu5U4lJq4RX8_Mi3Y_GZ5rqDUJdgnF_Bt5cWfyJJqGL0BicNpfoT34NWj9U9Oj_L7Vhz3OU032kcesWmHI",
    "Date": "Jul 2022",
    "Recommentation": "1 Recommendation",
    "Summary": "Purpose\nThis research aims to examine how two management strategies (symmetrical communication and inclusive management) work in handling workplace conflicts (interpersonal/organizational levels), especially with regard to employee advocacy and job turnover intentions.\n\nDesign/methodology/approach\nA total of three employee survey datasets were used to test hypotheses and research questions. Two secondary datasets were obtained in South Korea ( N = 600 and N = 285), and one dataset was collected in the USA ( N = 381). A series of hierarchical multiple regressions were performed for each dataset.\n\nFindings\nAll three studies showed that interpersonal workplace conflict increased not only job turnover but also advocacy. In addition, in South Korean employees, both symmetrical communication and inclusive management increased employee advocacy and decreased job turnover intentions. However, in the US data, only symmetrical communication had such effects, enhancing employee advocacy and lowering job turnover intentions.\n\nOriginality/value\nThe study provides insights for practitioners into how to handle workplace conflicts from the perspective of communication (symmetrical communication) and/or behavioral strategies (inclusive management). Also, as an index to examine the effectiveness of management strategies, this study suggests advocacy behavior of employees given its effect of “rallying the troops.”",
    "Option 1": "",
    "URL3": "",
    "Date2": "Jul 2022",
    "ETC": ""
  },
  {
    "Title": "Appetite for Natech Risk Information in Japan: Understanding Citizens’ Communicative Behavior Towards Risk Information Disclosure Around Osaka Bay",
    "URL": "https://www.researchgate.net/publication/361328552_Appetite_for_Natech_Risk_Information_in_Japan_Understanding_Citizens%27_Communicative_Behavior_Towards_Risk_Information_Disclosure_Around_Osaka_Bay?_sg=U6dBS_SuRkLKyUm7H8Y6bTawTS3JbYEjIhLEA30qmVdPXAzAVArM1txTCP-YpniTRdWmNDzng1DUcrc-W-kJ1o0hbo0",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/361328552_Appetite_for_Natech_Risk_Information_in_Japan_Understanding_Citizens%27_Communicative_Behavior_Towards_Risk_Information_Disclosure_Around_Osaka_Bay?_sg=U6dBS_SuRkLKyUm7H8Y6bTawTS3JbYEjIhLEA30qmVdPXAzAVArM1txTCP-YpniTRdWmNDzng1DUcrc-W-kJ1o0hbo0",
    "Date": "",
    "Recommentation": "6 Recommendations",
    "Summary": "Effective risk communication is essential for disaster risk management. Apart from empowering communities to make informed risk choices, risk information disclosure can also drastically enhance their disaster preparedness, especially concerning conjoint scenarios of technological and natural hazards (Natech). A fundamental precondition is the actual demand for such information. This study ventures to assess whether residents around Osaka Bay have this demand, or “appetite,” for risk information disclosure, as well as to understand their communicative behavior and perceived challenges in the Japanese context through the prism of the Situational Theory of Problem Solving. To test this framework under realistic conditions, data were collected through a household questionnaire survey from two urban areas near industrial complexes in Osaka Bay. The results show that identifying Natech risk information deficiency as a problem was not a statistically significant predictor for individuals’ motivation to communicate. However, their motivation increased as their perceived personal involvement with the situation rose, while the perceived obstacles in doing something about it exerted a negative influence on their motivation. Individuals’ motivation intensified their communicative actions to solve this problem. Public segmentation underscored the elevated public perceptions concerning the issue of risk information deficiency in nearly nine out of ten respondents. These findings indicate a strong community appetite for chemical and Natech risk information, which subsequently led to high situational motivation to engage in communicative action, particularly information acquisition. Risk management policy is suggested to focus on introducing chemical risk information disclosure regulatory initiatives to encourage citizen engagement.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/361328552_Appetite_for_Natech_Risk_Information_in_Japan_Understanding_Citizens%27_Communicative_Behavior_Towards_Risk_Information_Disclosure_Around_Osaka_Bay?_sg=U6dBS_SuRkLKyUm7H8Y6bTawTS3JbYEjIhLEA30qmVdPXAzAVArM1txTCP-YpniTRdWmNDzng1DUcrc-W-kJ1o0hbo0",
    "Date2": "Jun 2022",
    "ETC": ""
  },
  {
    "Title": "Election Fraud and Misinformation on Twitter: Author, Cluster, and Message Antecedents",
    "URL": "https://www.researchgate.net/publication/360280837_Election_Fraud_and_Misinformation_on_Twitter_Author_Cluster_and_Message_Antecedents?_sg=b0Ocbo2urVZX1e9_A26j90PVF9v2OLBAgbUybb47RqoWymOsrFW0BZ-B77r13Uj_Zc4AJMYYmMfT7DbGuQoYJIGU4mI",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/360280837_Election_Fraud_and_Misinformation_on_Twitter_Author_Cluster_and_Message_Antecedents?_sg=b0Ocbo2urVZX1e9_A26j90PVF9v2OLBAgbUybb47RqoWymOsrFW0BZ-B77r13Uj_Zc4AJMYYmMfT7DbGuQoYJIGU4mI",
    "Date": "",
    "Recommentation": "",
    "Summary": "This study determined the antecedents of diffusion scope (total audience), speed (number of adopters/time), and shape (broadcast vs. person-to-person transmission) for true vs. fake news about a falsely claimed stolen 2020 US Presidential election across clusters of users that responded to one another’s tweets (“user clusters”). We examined 31,128 tweets with links to fake vs. true news by 20,179 users to identify 1,069 user clusters via clustering analysis. We tested whether attributes of authors (experience, followers, following, total tweets), time (date), or tweets (link to fake [vs. true] news, retweets) affected diffusion scope, speed, or shape, across user clusters via multilevel diffusion analysis. These tweets showed no overall diffusion pattern; instead, specific explanatory variables determined their scope, speed, and shape. Compared to true news tweets, fake news tweets started earlier and showed greater broadcast influence (greater diffusion speed), scope, and person-to-person influence. Authors with more experience and smaller user clusters both showed greater speed but less scope and less person-to-person influence. Likewise, later tweets showed slightly more broadcast influence, less scope, and more person-to-person influence. By contrast, users with more followers showed less broadcast influence but greater scope and slightly more person-to-person influence. These results highlight the earlier instances of fake news and the greater diffusion speed of fake news in smaller user clusters and by users with fewer followers, so they suggest that monitors can detect fake news earlier by focusing on earlier tweets, smaller user clusters, and users with fewer followers.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/360280837_Election_Fraud_and_Misinformation_on_Twitter_Author_Cluster_and_Message_Antecedents?_sg=b0Ocbo2urVZX1e9_A26j90PVF9v2OLBAgbUybb47RqoWymOsrFW0BZ-B77r13Uj_Zc4AJMYYmMfT7DbGuQoYJIGU4mI",
    "Date2": "Apr 2022",
    "ETC": ""
  },
  {
    "Title": "Serving the Greater Social Good for Personal Gain: Effects of Polite Disagreements in Online Debates",
    "URL": "https://www.researchgate.net/publication/355984949_Serving_the_Greater_Social_Good_for_Personal_Gain_Effects_of_Polite_Disagreements_in_Online_Debates?_sg=6c2UtpJnwJ6IGEh0j9gybSTOb_jHMXNqvhKztFxpicF8BKdCvAxX3TQugQYoa48L_PcacaUNy7M6sY3jS-heUPlCsIU",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/355984949_Serving_the_Greater_Social_Good_for_Personal_Gain_Effects_of_Polite_Disagreements_in_Online_Debates?_sg=6c2UtpJnwJ6IGEh0j9gybSTOb_jHMXNqvhKztFxpicF8BKdCvAxX3TQugQYoa48L_PcacaUNy7M6sY3jS-heUPlCsIU",
    "Date": "",
    "Recommentation": "2 Recommendations",
    "Summary": "Asynchronous, anonymous online debaters might be less likely than face-to-face debaters to value their public self-image (face), and thus disagree more freely. In this study, we examined whether polite disagreements (as opposed to rude ones) help online debaters win over audience members. An analysis of the most voted-on 100 political debates on Debate.org (200 debaters; 1,750 voters; 472,652 words) showed that debate initiators who used politer face-saving strategies to disagree (i.e., using expressions such as negatives with agree words rather than disagree or harsh rejection words) were more likely to receive more audience votes and win their debates. These results suggest that politeness tactics during online debates increase effectiveness, align with normative ideals, and yield pragmatic gain.",
    "Option 1": "Publisher preview available",
    "URL3": "https://www.researchgate.net/publication/355984949_Serving_the_Greater_Social_Good_for_Personal_Gain_Effects_of_Polite_Disagreements_in_Online_Debates?_sg=6c2UtpJnwJ6IGEh0j9gybSTOb_jHMXNqvhKztFxpicF8BKdCvAxX3TQugQYoa48L_PcacaUNy7M6sY3jS-heUPlCsIU",
    "Date2": "Apr 2022",
    "ETC": ""
  },
  {
    "Title": "An Oscillatory Path to Vaccination: The Roles of Normative and Epistemic Factors in Explaining Vaccination Hesitancy in COVID-19",
    "URL": "https://www.researchgate.net/publication/359654369_An_Oscillatory_Path_to_Vaccination_The_Roles_of_Normative_and_Epistemic_Factors_in_Explaining_Vaccination_Hesitancy_in_COVID-19?_sg=qaChxb_RFK2ltvw0NAta07Ny8K5P6TH_SMNO8pnlWYnmNgZ-e9UKPoGLR71av-o-3qZeIkWnEsjpQMrRjwk9fQg3-wE",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/359654369_An_Oscillatory_Path_to_Vaccination_The_Roles_of_Normative_and_Epistemic_Factors_in_Explaining_Vaccination_Hesitancy_in_COVID-19?_sg=qaChxb_RFK2ltvw0NAta07Ny8K5P6TH_SMNO8pnlWYnmNgZ-e9UKPoGLR71av-o-3qZeIkWnEsjpQMrRjwk9fQg3-wE",
    "Date": "Mar 2022",
    "Recommentation": "3 Recommendations",
    "Summary": "This study examined the roles of normative and epistemic factors in influencing individuals' reluctance to be vaccinated during the COVID-19 pandemic. Individuals' ethical orientations (IEO; teleology vs. deontology) were introduced as normative characteristics, while COVID-19 vaccine conspiracy beliefs and vaccine knowledge were addressed as issue-specific epistemic factors. We conducted two online surveys to investigate each of these three factors' influences on the level of Americans' reluctance to receive COVID-19 vaccines. Combinations of these factors that predict COVID-19 vaccination hesitancy levels were also explored to provide integrated perspectives in the specific vaccination context. Our findings demonstrated the positive association between IEO and reluctance to receive COVID-19 vaccines. Significant interactions between 1) COVID-19 vaccine conspiracy beliefs and IEO and 2) conspiracy beliefs and vaccine knowledge were also identified. Implications, limitations, and suggestions for future study were addressed.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Mar 2022",
    "ETC": ""
  },
  {
    "Title": "From messaging to behavioral strategy: Constructing a model of relationship- and action-focused crisis communication principles",
    "URL": "https://www.researchgate.net/publication/359604973_From_messaging_to_behavioral_strategy_Constructing_a_model_of_relationship-_and_action-focused_crisis_communication_principles?_sg=etgUz3Ewq1ubtyCAlgOV_-VHOhHVXkbGtdJY9lVKYcsIKNC6ifLR_6NhFuHSRcRP7M2td11BnLiOKtf7KnOkZN3QV4Y",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/359604973_From_messaging_to_behavioral_strategy_Constructing_a_model_of_relationship-_and_action-focused_crisis_communication_principles?_sg=etgUz3Ewq1ubtyCAlgOV_-VHOhHVXkbGtdJY9lVKYcsIKNC6ifLR_6NhFuHSRcRP7M2td11BnLiOKtf7KnOkZN3QV4Y",
    "Date": "",
    "Recommentation": "1 Recommendation",
    "Summary": "Existing crisis communication theories are useful in guiding organizations to choose crisis responses that help buffer them from a crisis by shaping how publics interpret the crisis. However, in crises, publics who suffer from negative consequences expect organizations to focus on problem-solving behaviors and eventual restoration of relationships. As a reflective theorizing of the perspectives of publics, this study introduces six relationship-and action-focused principles-relationship, accountability, promptness, inclusivity, disclosure, and symmetry (RAPIDS)-that emphasize how organizations should redress the need for problem solving and bridge with publics to build and maintain organization-public relationships before, during, and after a crisis. A survey (N = 436) was conducted in the United States to test the construct reliability and validity of RAPIDS for three crises. The findings show conceptual and operational adequacy with an overarching latent construct (a second-order factor structure) encompassing all six principles. Furthermore, the construct is positively associated with forgiveness.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/359604973_From_messaging_to_behavioral_strategy_Constructing_a_model_of_relationship-_and_action-focused_crisis_communication_principles?_sg=etgUz3Ewq1ubtyCAlgOV_-VHOhHVXkbGtdJY9lVKYcsIKNC6ifLR_6NhFuHSRcRP7M2td11BnLiOKtf7KnOkZN3QV4Y",
    "Date2": "Mar 2022",
    "ETC": ""
  },
  {
    "Title": "In search of communication excellence: Public relations' value, empowerment, and structure in strategic management",
    "URL": "https://www.researchgate.net/publication/346952365_In_search_of_communication_excellence_Public_relations%27_value_empowerment_and_structure_in_strategic_management?_sg=ikpfDeaRNQDAV_kwNFUwOJU5dioGmrcKrkzeiC6loEFpfk_eoEmWnZs7j6BjpJcFbcFNOy9T9bZ1a_42QJqJZzP1bS8",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/346952365_In_search_of_communication_excellence_Public_relations%27_value_empowerment_and_structure_in_strategic_management?_sg=ikpfDeaRNQDAV_kwNFUwOJU5dioGmrcKrkzeiC6loEFpfk_eoEmWnZs7j6BjpJcFbcFNOy9T9bZ1a_42QJqJZzP1bS8",
    "Date": "",
    "Recommentation": "9 Recommendations",
    "Summary": "The multifaceted roles of public relations are not well-understood in strategic management. Thus, this study reviews strategic management literature and presents empirical evidence on the relevance of public relations to strategic management. Using data collected from public relations practitioners and organizational leaders in the Generally Accepted Practice (GAP) survey conducted by the University of Southern California (USC) and the Excellence Study commissioned by the International Association of Business Communicators (IABC) Research Foundation, the dynamics between the public relations function and organizational outcomes (i.e., corporate strategic orientation and corporate legitimacy performance) are explored. The findings present new empirical evidence of the contributions that public relations makes to strategic management (i.e., its value), the conditions under which public relations makes more contributions to strategic management (i.e., its empowerment) and the differences between marketing-dominant and public relations-independent communication departments in terms of their focus and effects on organizational outcomes (i.e., its structure). The relevance of the findings to the strategic management role of public relations today is discussed.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/346952365_In_search_of_communication_excellence_Public_relations%27_value_empowerment_and_structure_in_strategic_management?_sg=ikpfDeaRNQDAV_kwNFUwOJU5dioGmrcKrkzeiC6loEFpfk_eoEmWnZs7j6BjpJcFbcFNOy9T9bZ1a_42QJqJZzP1bS8",
    "Date2": "Jan 2022",
    "ETC": ""
  },
  {
    "Title": "Cognitive arrest in problem solving Kim Grunig and Ortez (in press Dewey Studies)",
    "URL": "https://www.researchgate.net/publication/356588306_Cognitive_arrest_in_problem_solving_Kim_Grunig_and_Ortez_in_press_Dewey_Studies?_sg=SDwFv2fHZaoY2wyPag7sja5sR1WEGbBYX-mVC4zNvRy-4-j_O9qpSSrjdClb5-jQy4mSW2ubuai6sgPGj-WMpV9_OSM",
    "Type": "Preprint",
    "URL2": "https://www.researchgate.net/publication/356588306_Cognitive_arrest_in_problem_solving_Kim_Grunig_and_Ortez_in_press_Dewey_Studies?_sg=SDwFv2fHZaoY2wyPag7sja5sR1WEGbBYX-mVC4zNvRy-4-j_O9qpSSrjdClb5-jQy4mSW2ubuai6sgPGj-WMpV9_OSM",
    "Date": "Nov 2021",
    "Recommentation": "3 Recommendations",
    "Summary": "Accepted to \"Dewey Studies\"\nSpecial Issues -- \"After the insurrection: Addressing the crisis in liberal democracy\"",
    "Option 1": "",
    "URL3": "",
    "Date2": "Nov 2021",
    "ETC": ""
  },
  {
    "Title": "Paradigms of Public Relations in an Age of Digitalisation",
    "URL": "https://www.researchgate.net/publication/350772012_Paradigms_of_Public_Relations_in_an_Age_of_Digitalisation?_sg=oREeEFB7YSfA88_E3MYilHDKwdT1hl8oMxi_WOOLn8WryFmqHfpwpLK1n_9ixQYlrlv8YB9fZcZBLcZ7NLnpReuwuS4",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/350772012_Paradigms_of_Public_Relations_in_an_Age_of_Digitalisation?_sg=oREeEFB7YSfA88_E3MYilHDKwdT1hl8oMxi_WOOLn8WryFmqHfpwpLK1n_9ixQYlrlv8YB9fZcZBLcZ7NLnpReuwuS4",
    "Date": "",
    "Recommentation": "7 Recommendations",
    "Summary": "",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/350772012_Paradigms_of_Public_Relations_in_an_Age_of_Digitalisation?_sg=oREeEFB7YSfA88_E3MYilHDKwdT1hl8oMxi_WOOLn8WryFmqHfpwpLK1n_9ixQYlrlv8YB9fZcZBLcZ7NLnpReuwuS4",
    "Date2": "Apr 2021",
    "ETC": ""
  },
  {
    "Title": "Advocates or adversaries? Explicating within-border foreign publics’ role in shaping soft power through megaphoning and echoing",
    "URL": "https://www.researchgate.net/publication/337471377_Advocates_or_adversaries_Explicating_within-border_foreign_publics%27_role_in_shaping_soft_power_through_megaphoning_and_echoing?_sg=83Gmc8RKvfl6dr9oxYIY9bngy0VD3BJwli6mQKHtXz4gkSDMcQD88L02XHuiqqxPcsnprmZHle8dz6a8Bk9dQAcDIHk",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/337471377_Advocates_or_adversaries_Explicating_within-border_foreign_publics%27_role_in_shaping_soft_power_through_megaphoning_and_echoing?_sg=83Gmc8RKvfl6dr9oxYIY9bngy0VD3BJwli6mQKHtXz4gkSDMcQD88L02XHuiqqxPcsnprmZHle8dz6a8Bk9dQAcDIHk",
    "Date": "",
    "Recommentation": "2 Recommendations",
    "Summary": "This study presents an empirical test and a conceptual account of the role of within-border foreign publics (WBFPs) as important communicative influencers, explicating how shared experiences shape the ideas and opinions of a foreign country. The study focuses on two communicative concepts, megaphoning and echoing, and finds they explicate network impacts of sociological public diplomacy. The information megaphoned by the WBFP (e.g., international students) is echoed in their relational networks back home. The findings provide evidence that the megaphoning behaviors of WBFPs are significantly related to the directionality and magnitude of echoing among their social networks in their home countries.",
    "Option 1": "Publisher preview available",
    "URL3": "https://www.researchgate.net/publication/337471377_Advocates_or_adversaries_Explicating_within-border_foreign_publics%27_role_in_shaping_soft_power_through_megaphoning_and_echoing?_sg=83Gmc8RKvfl6dr9oxYIY9bngy0VD3BJwli6mQKHtXz4gkSDMcQD88L02XHuiqqxPcsnprmZHle8dz6a8Bk9dQAcDIHk",
    "Date2": "Mar 2021",
    "ETC": ""
  },
  {
    "Title": "A conceptual genealogy of the situational theory of problem solving: Reconceptualizing communication for strategic behavioral communication management",
    "URL": "https://www.researchgate.net/publication/349191034_A_conceptual_genealogy_of_the_situational_theory_of_problem_solving_Reconceptualizing_communication_for_strategic_behavioral_communication_management?_sg=Nfp_Du5Q7qSO053FFCDGq3JLyORxg6KfUAcVimoswk0s7edYTu-axJx2350PTdddEoDsKFEpMK5nDawpzHneb0DkmK4",
    "Type": "Chapter",
    "URL2": "https://www.researchgate.net/publication/349191034_A_conceptual_genealogy_of_the_situational_theory_of_problem_solving_Reconceptualizing_communication_for_strategic_behavioral_communication_management?_sg=Nfp_Du5Q7qSO053FFCDGq3JLyORxg6KfUAcVimoswk0s7edYTu-axJx2350PTdddEoDsKFEpMK5nDawpzHneb0DkmK4",
    "Date": "",
    "Recommentation": "",
    "Summary": "The situational theory of problem solving (STOPS) was constructed with the premise that communicative behaviors are purposive and epiphenomenal to problem solving. It inherits from the situational theory of publics (STP) the assumption that communication is not just what senders do to change receivers’ attitudes and behaviors – rather, communication is what individuals do to cope with problematic life situations. While STP explains the role of information in decision making, STOPS explains communicative behaviors of publics in the context of problematic situations. The shift of focus from decisional situations to problematic situations provides scholars with a new theoretical foundation to conceptualize public relations. STOPS has shifted the focus of public relations theory from generating media effects to influence the general public to understanding why and how individuals become motivated to organize into issue-specific publics. STOPS has been widely applied to multiple contexts, including health communication, employee communication, environmental communication, crisis communication, and public diplomacy.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/349191034_A_conceptual_genealogy_of_the_situational_theory_of_problem_solving_Reconceptualizing_communication_for_strategic_behavioral_communication_management?_sg=Nfp_Du5Q7qSO053FFCDGq3JLyORxg6KfUAcVimoswk0s7edYTu-axJx2350PTdddEoDsKFEpMK5nDawpzHneb0DkmK4",
    "Date2": "Feb 2021",
    "ETC": "Handbook of Communication Science: Public Relations"
  },
  {
    "Title": "15 The four models of public relations and their research legacy",
    "URL": "https://www.researchgate.net/publication/349183517_15_The_four_models_of_public_relations_and_their_research_legacy?_sg=lhuehUf3Q0dB-ugK-4x5WTvHOi1fjWC3ub6xsJFMDosirmKkIdfnITncfS-OGiGjEoPyjS7iWk34oyijZMyKiakwKhw",
    "Type": "Chapter",
    "URL2": "https://www.researchgate.net/publication/349183517_15_The_four_models_of_public_relations_and_their_research_legacy?_sg=lhuehUf3Q0dB-ugK-4x5WTvHOi1fjWC3ub6xsJFMDosirmKkIdfnITncfS-OGiGjEoPyjS7iWk34oyijZMyKiakwKhw",
    "Date": "",
    "Recommentation": "12 Recommendations",
    "Summary": "",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/349183517_15_The_four_models_of_public_relations_and_their_research_legacy?_sg=lhuehUf3Q0dB-ugK-4x5WTvHOi1fjWC3ub6xsJFMDosirmKkIdfnITncfS-OGiGjEoPyjS7iWk34oyijZMyKiakwKhw",
    "Date2": "Feb 2021",
    "ETC": "Public Relations"
  },
  {
    "Title": "The power of gossip: contextual talk in tourism communication",
    "URL": "https://www.researchgate.net/publication/347662530_The_power_of_gossip_contextual_talk_in_tourism_communication?_sg=o6NJUy5-8ObC_0hJC-0p6wl5KNaE27wXSP7cRzLc-kg0lys5CdA5p9ZoLWxHNbJ-iGY8269zgk0pY7zCf2JItYV0nYI",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/347662530_The_power_of_gossip_contextual_talk_in_tourism_communication?_sg=o6NJUy5-8ObC_0hJC-0p6wl5KNaE27wXSP7cRzLc-kg0lys5CdA5p9ZoLWxHNbJ-iGY8269zgk0pY7zCf2JItYV0nYI",
    "Date": "Dec 2020",
    "Recommentation": "1 Recommendation",
    "Summary": "This study investigates the role of individuals’ accidental, contextual talking – rather than planned, goal-oriented conversation – about tourism to illuminate its influences on touristic motivation and communicative behaviors. Contextual talking in daily life can trigger internalized and situational motivation toward information behaviors regarding tourist concern. Two comparative studies were conducted to provide a causal account of touristic information behavior in the U.S. and China. The studies’ results suggest the role of contextual talking in triggering situational motivation, which explains the substantial variance of communicative actions regarding tourist destinations. Moreover, an alternative model was specified and tested; this model proposes that tourist concern still functions as a significant predictor of active communication. This study discusses the implications of the role of contextual talk and its domino effect.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Dec 2020",
    "ETC": ""
  },
  {
    "Title": "Ashamed Caregivers: Self-Stigma, Information, and Coping among Dementia Patient Families",
    "URL": "https://www.researchgate.net/publication/346571121_Ashamed_Caregivers_Self-Stigma_Information_and_Coping_among_Dementia_Patient_Families?_sg=QLUlhPSOgyL5x5wlMrwMynlsCOUQqjXk3llmzxynV5x1KSJeK27J7V2TTzOjsuyiChCDay3vetxawEyq37s9tMT6QI4",
    "Type": "Preprint",
    "URL2": "https://www.researchgate.net/publication/346571121_Ashamed_Caregivers_Self-Stigma_Information_and_Coping_among_Dementia_Patient_Families?_sg=QLUlhPSOgyL5x5wlMrwMynlsCOUQqjXk3llmzxynV5x1KSJeK27J7V2TTzOjsuyiChCDay3vetxawEyq37s9tMT6QI4",
    "Date": "Dec 2020",
    "Recommentation": "3 Recommendations",
    "Summary": "The number of people living with dementia increases almost every year, and the majority of the care system for these individuals is often made up of close family members. This study investigates the relationship between family caregivers' cross-checking of information with healthcare providers and patient health outcomes. Specifically, we examined whether this relationship was mediated by caregivers' enhanced coping efficacy. We also tested the moderation effect of family caregivers' affiliate stigma on information cross-checking, coping efficacy, and coping outcomes. Using a survey of 226 family caregivers of dementia patients in South Korea, this study tested the moderated mediation model with the PROCESS macro. Results indicate that low affiliate stigma moderates coping efficacy on the relationship between information cross-checking and dementia patients' health outcomes. Further implications for family caregiving and general dementia care are discussed.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Dec 2020",
    "ETC": ""
  },
  {
    "Title": "Pseudo-Information, Media, Publics, and the Failing Marketplace of Ideas: Theory",
    "URL": "https://www.researchgate.net/publication/343989800_Pseudo-Information_Media_Publics_and_the_Failing_Marketplace_of_Ideas_Theory?_sg=Taf5B-YX1ruMbH6xGV9Xu_1DutxFAqoquLZ1-z4I2WKGTjYFuSwepwOZAjfgvgjo9DPZTf8Rc7MIOcthOllMa3k4lKU",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/343989800_Pseudo-Information_Media_Publics_and_the_Failing_Marketplace_of_Ideas_Theory?_sg=Taf5B-YX1ruMbH6xGV9Xu_1DutxFAqoquLZ1-z4I2WKGTjYFuSwepwOZAjfgvgjo9DPZTf8Rc7MIOcthOllMa3k4lKU",
    "Date": "",
    "Recommentation": "6 Recommendations",
    "Summary": "The explosive usage in recent years of the terms “fake news” and “posttruth” reflects worldwide frustration and concern about rampant social problems created by pseudo-information. Our digital networked society and newly emerging media platforms foster public misunderstanding of social affairs, which affects almost all aspects of individual life. The cost of lay citizens’ misunderstandings or crippled lay informatics can be high. Pseudo-information is responsible for deficient social systems and institutional malfunction. We thus ask questions and collect knowledge about the life of pseudo-information and the cognitive and communicative modus operandi of lay publics, as well as how to solve the problem of pseudo-information through understanding the changing media environment in this “truth-be-damned” era of information crisis.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/343989800_Pseudo-Information_Media_Publics_and_the_Failing_Marketplace_of_Ideas_Theory?_sg=Taf5B-YX1ruMbH6xGV9Xu_1DutxFAqoquLZ1-z4I2WKGTjYFuSwepwOZAjfgvgjo9DPZTf8Rc7MIOcthOllMa3k4lKU",
    "Date2": "Aug 2020",
    "ETC": ""
  },
  {
    "Title": "On Evolving Nature of Relationship by Perspective Mutuality: Reconceptualizing Relationship Typology Between Organization and Its Publics",
    "URL": "https://www.researchgate.net/publication/343916844_On_Evolving_Nature_of_Relationship_by_Perspective_Mutuality_Reconceptualizing_Relationship_Typology_Between_Organization_and_Its_Publics?_sg=5PvICS10n1RVTr0qfHp4bHGfcEKHBW4qgXCLWOsBi2svZ9JIDoFXpYArbhQ-wIa8UNErwPve-TpOJlD3_5qcw8_a3Os",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/343916844_On_Evolving_Nature_of_Relationship_by_Perspective_Mutuality_Reconceptualizing_Relationship_Typology_Between_Organization_and_Its_Publics?_sg=5PvICS10n1RVTr0qfHp4bHGfcEKHBW4qgXCLWOsBi2svZ9JIDoFXpYArbhQ-wIa8UNErwPve-TpOJlD3_5qcw8_a3Os",
    "Date": "",
    "Recommentation": "2 Recommendations",
    "Summary": "To address conceptual and methodological issues regarding the exchange–communal relationship typology in public relations scholarship, this study reconceptualizes and validates three relationship types—egoistic, provident, and communal relationships. Two distinct relationship perspectives, organization-oriented and public-oriented, are also explored. The results of the two studies, focusing on an organization’s respective relationships with internal (i.e., employees) and external (i.e., consumers) publics, demonstrate the construct reliability and validity of newly conceptualized relationship types. The association between relationship types and relationship quality—trust, control mutuality, commitment, and satisfaction—is examined with structural equation modeling (SEM) and each path of two studies was compared through multigroup analysis. Theoretical and practical implications for public relations disciplines are discussed.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/343916844_On_Evolving_Nature_of_Relationship_by_Perspective_Mutuality_Reconceptualizing_Relationship_Typology_Between_Organization_and_Its_Publics?_sg=5PvICS10n1RVTr0qfHp4bHGfcEKHBW4qgXCLWOsBi2svZ9JIDoFXpYArbhQ-wIa8UNErwPve-TpOJlD3_5qcw8_a3Os",
    "Date2": "Aug 2020",
    "ETC": ""
  },
  {
    "Title": "Values of Government Public Relations for a Rocky Road to Participatory Democracy: Testing Public Engagement, Empowerment, and Serenity Hypotheses in Public Sector Communication",
    "URL": "https://www.researchgate.net/publication/343050752_Values_of_Government_Public_Relations_for_a_Rocky_Road_to_Participatory_Democracy_Testing_Public_Engagement_Empowerment_and_Serenity_Hypotheses_in_Public_Sector_Communication?_sg=0SQebwy9SntGQPsTUN__hYqp3ndfJBNTuXWiDWa5kyaeljGb1fl3GY-fC6Y2an1kzRY7mkTMuKsh68SRg1KZCSD-0BQ",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/343050752_Values_of_Government_Public_Relations_for_a_Rocky_Road_to_Participatory_Democracy_Testing_Public_Engagement_Empowerment_and_Serenity_Hypotheses_in_Public_Sector_Communication?_sg=0SQebwy9SntGQPsTUN__hYqp3ndfJBNTuXWiDWa5kyaeljGb1fl3GY-fC6Y2an1kzRY7mkTMuKsh68SRg1KZCSD-0BQ",
    "Date": "",
    "Recommentation": "1 Recommendation",
    "Summary": "Voluntary citizen attention and actions are key to successful public-sector communication. We investigated the conditions which increase such attention and actions using the situational theory of problem solving (STOPS) and government-citizen relationships (GCRs). Using three national issues consisting of an environmental issue, a social issue, and a political issue from South Korea (N=275), this study examined three hypotheses regarding public engagement effect (the effect of GCRs on political conversations on national issues), government empowerment effect (the effects of GCRs and issue-specific trust toward government on constraint recognition), and public serenity effect (the effect of issue-specific trust on problem recognition and involvement recognition). We found significant public engagement and government empowerment effects and partially significant public serenity effect. The results of the public serenity investigation found that issue-specific trust toward government was significant with problem recognition but insignificant with involvement recognition. Consequently, the findings illustrate strategic values in government-citizen relationships on public engagement, empowerment, and serenity to enable participatory democracy.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/343050752_Values_of_Government_Public_Relations_for_a_Rocky_Road_to_Participatory_Democracy_Testing_Public_Engagement_Empowerment_and_Serenity_Hypotheses_in_Public_Sector_Communication?_sg=0SQebwy9SntGQPsTUN__hYqp3ndfJBNTuXWiDWa5kyaeljGb1fl3GY-fC6Y2an1kzRY7mkTMuKsh68SRg1KZCSD-0BQ",
    "Date2": "Jul 2020",
    "ETC": ""
  },
  {
    "Title": "Lost in Informational Paradise: Cognitive Arrest to Epistemic Inertia in Problem Solving",
    "URL": "https://www.researchgate.net/publication/336535695_Lost_in_Informational_Paradise_Cognitive_Arrest_to_Epistemic_Inertia_in_Problem_Solving?_sg=P16G1aif1zRoWXVkDo7a57AC_lKSdvVdHs_NWohEpagWXsFyLcDqjj9nVQAghYNuFFu9QbesPwu7YQejBQ1umbLafH0",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/336535695_Lost_in_Informational_Paradise_Cognitive_Arrest_to_Epistemic_Inertia_in_Problem_Solving?_sg=P16G1aif1zRoWXVkDo7a57AC_lKSdvVdHs_NWohEpagWXsFyLcDqjj9nVQAghYNuFFu9QbesPwu7YQejBQ1umbLafH0",
    "Date": "Oct 2019",
    "Recommentation": "6 Recommendations",
    "Summary": "We conceptualize two cognitive modi operandi by which lay individuals (cf. experts) solve everyday life problems: cognitive retrogression and cognitive progression. The key demarcation between these two strategies is when a conclusion is finalized and how one’s cognitive and communicative efforts are expended in a problematic situation. Using these two concepts of cognitive strategies in problem solving, we explicate the emerging processes of cognitive arrest and epistemic inertia in the digital age and changing information environment. We apply the cognitive and communicative account to an exemplary case of cognitive arrest among lay publics: that of conspiracism and close-mindedness.",
    "Option 1": "",
    "URL3": "",
    "Date2": "Oct 2019",
    "ETC": ""
  },
  {
    "Title": "Who are publics in public diplomacy? Proposing a taxonomy of foreign publics as an intersection between symbolic environment and behavioral experiences",
    "URL": "https://www.researchgate.net/publication/326056416_Who_are_publics_in_public_diplomacy_Proposing_a_taxonomy_of_foreign_publics_as_an_intersection_between_symbolic_environment_and_behavioral_experiences?_sg=IQPCTiXrqZdwqhAgBNNreCxOzpu3gnx1iqG-KjK_1hEpHOcGE-PssqP-vh7Kzw2ksIMl6iPjA8-PHW-xCTa5ZJKa92Y",
    "Type": "Article",
    "URL2": "https://www.researchgate.net/publication/326056416_Who_are_publics_in_public_diplomacy_Proposing_a_taxonomy_of_foreign_publics_as_an_intersection_between_symbolic_environment_and_behavioral_experiences?_sg=IQPCTiXrqZdwqhAgBNNreCxOzpu3gnx1iqG-KjK_1hEpHOcGE-PssqP-vh7Kzw2ksIMl6iPjA8-PHW-xCTa5ZJKa92Y",
    "Date": "",
    "Recommentation": "4 Recommendations",
    "Summary": "Existing literature on public diplomacy has generally defined foreign publics as the global constituents with whom a country builds relationships through its public diplomacy efforts. However, not all foreign publics are the same; they represent a collection of separate public opinions. As such, foreign publics need to be segmented and differentiated in order for countries to strategically invest their resources and optimize public diplomacy outcomes. In light of this, this paper proposes a taxonomy which approaches the concept of foreign publics as an intersection between symbolic environment and behavioral experiences. By classifying foreign publics into four segments (i.e., ambassadorial, advocational, accusational, and adversarial), this paper explains the formation and characteristics of each segment of foreign publics, as well as their implications for a country’s public diplomacy efforts.",
    "Option 1": "Full-text available",
    "URL3": "https://www.researchgate.net/publication/326056416_Who_are_publics_in_public_diplomacy_Proposing_a_taxonomy_of_foreign_publics_as_an_intersection_between_symbolic_environment_and_behavioral_experiences?_sg=IQPCTiXrqZdwqhAgBNNreCxOzpu3gnx1iqG-KjK_1hEpHOcGE-PssqP-vh7Kzw2ksIMl6iPjA8-PHW-xCTa5ZJKa92Y",
    "Date2": "Mar 2019",
    "ETC": ""
  }
];